-- --------------------------------------------------------
-- Hôte :                        127.0.0.1
-- Version du serveur:           10.4.0-MariaDB - mariadb.org binary distribution
-- SE du serveur:                Win64
-- HeidiSQL Version:             9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Export de la structure de la base pour boulder_dash
DROP DATABASE IF EXISTS `boulder_dash`;
CREATE DATABASE IF NOT EXISTS `boulder_dash` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `boulder_dash`;

-- Export de la structure de la table boulder_dash. level
DROP TABLE IF EXISTS `level`;
CREATE TABLE IF NOT EXISTS `level` (
  `id` int(11) NOT NULL,
  `time` int(11) NOT NULL,
  `number_diamond` int(11) NOT NULL,
  `level_map` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Export de données de la table boulder_dash.level : ~10 rows (environ)
/*!40000 ALTER TABLE `level` DISABLE KEYS */;
INSERT INTO `level` (`id`, `time`, `number_diamond`, `level_map`) VALUES
	(1, 120, 10, 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB;BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB;BBBBOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOBBBB;BBBBODDBBBBIBBBBBBBBRRBBBBBBBBBBBBBBBRRRRRDOBBBB;BBBBOBBRRBBIBDBBBBBBBBBBBBB   1BBBBRBBBBRDDOBBBB;BBBBOBBBBBBIBBBBBBRRBBBBBRRRRRBBBBBDRBBBBBBOBBBB;BBBBOBBBBBBIBBBBBBBRBBBBBBBRRBBRBBBBBBBBBBBOBBBB;BBBBOBRBBBBIBBBBBBBBBBBBBBBBBBBDBBBBBBBBBBBOBBBB;BBBBOBBBBBBIBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBOBBBB;BBBBOBBBBBBIIIIIIIRRRBBBIIIIIIIIIIIIIIIIIIIOBBBB;BBBBOBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBRRBBOBBBB;BBBBOBBBBBBBBBBBBBBBBBBBBBBBBBBBBRBBBBBBBBBOBBBB;BBBBOBBBBBBRRRRBBBBBBBBBBBBBBDBRRRBBBBBBBBBOBBBB;BBBBOBBBBBBBBRRBBBBDDBBBBRRBBBBBBDBBBBBBBBROBBBB;BBBBOBBRBBBBBBRBBBBBBBBBBBBBBBBBBBBBBBBBBRBOBBBB;BBBBOBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBRBBOBBBB;BBBBORRRRBBIIIIIIIIIIIIIIIIIIIIIIIIIIBBBRDBOBBBB;BBBBOBBBBBBIBBRBDRBBBBBBBBBBBBBBBBBBBBBBRBBOBBBB;BBBBODBBRRBIBBBBBBBBBBBBBRBBBBBBDDBBBBBBBBBOBBBB;BBBBOBBBBBBIBBBBBRRRBBBBBRBBBBBBBBBBBBBBBBBOBBBB;BBBBOBRBBBBIBBBBBBBBBBBRRRBBBBBRRRBBBBBBBBBOBBBB;BBBBOBBPBBRIBBBBBBBBBBBBBBBBBBBBRRBBBBBBBBBOBBBB;BBBBOBBBBBDIBBRRBDBBBBBBBBBBBBBBBBBBBBBDDBBOBBBB;BBBBOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOEOOOBBBB;BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB;BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.'),
	(2, 120, 20, 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB;BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB;BBBBOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOBBBB;BBBBOBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBOBBBB;BBBBOBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBOBBBB;BBBBOBBIIIIIIIIIIIIIIBBBBBBIIIIIIIIIIIIIIBBOBBBB;BBBBOBBIBBBBBBBBBBBBIBBBBBBIBBBBBBBBBBBBIBBOBBBB;BBBBOBBIDDDDDDDDDDDDIBBBBBBIDDDDDDDDDDDDIBBOBBBB;BBBBOBBIDDDDDDDDDDDDIBBBBBBIDDDDDDDDDDDDIBBOBBBB;BBBBOBBIBRRRRRRRRRRBIBBBBBBIBRRRRRRRRRRBIBBOBBBB;BBBBOBBIBRRRRRRRRRRBIBBBBBBIBRRRRRRRRRRBIBBOBBBB;BBBBOBBIBRRRRRRRRRRBIBBBBBBIBRRRRRRRRRRBIBBOBBBB;BBBBOBBIBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBIBBOBBBB;BBBBOBBI            IIIIIIII            IBBOBBBB;BBBBOBBI            IBBBBBBI            IBBOBBBB;BBBBOBBI            IBBBBEBI            IBBOBBBB;BBBBOBBI            IBBBBBBI            IBBOBBBB;BBBBOBBI            IBBBBBBI            IBBOBBBB;BBBBOBBI            IBBBBBBI            IBBOBBBB;BBBBOBBI            IBBBBBBI            IBBOBBBB;BBBBOBBI P          IBBBBBBI            IBBOBBBB;BBBBOBBIIIIIIIIIIIIIIBBBBBBIIIIIIIIIIIIIIBBOBBBB;BBBBOBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBOBBBB;BBBBOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOBBBB;BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB;BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.'),
	(3, 180, 8, 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB;BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB;BBBBOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOBBBB;BBBBOIDBBBPBBBBBBBBBBBBBBBBBBBBBBBBBRRBBBDIOBBBB;BBBBODIBBBRRRBBBBBBBBBRRBBBBBBBBBBBBBBBBBIDOBBBB;BBBBORBIBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBIBBOBBBB;BBBBOBBBIBBBBBBIBBBBBBBBBBBBBBBBBIBBBBBIBBBOBBBB;BBBBOBBBBIBBBBBBIBBBBRBBBBIIBBBBBBIBBBIBBBBOBBBB;BBBBOBBBBBIBBBBBBIBBBBBBBIBBIBBBBBBIDIBRRBBOBBBB;BBBBOBBRBBBIBBBBBBIBBBBBIBBBBIBBBBBBIDBBBBBOBBBB;BBBBOBBBRBBBIBBBBRBIBBBIBBBBBBIBBBBBBIBBBBBOBBBB;BBBBOBBBBBBBBIBBBRBBIDIBBRRBBBBIBBBBBBIBBBBOBBBB;BBBBOBBBBBBBBBIBBRBBBIBBBBBBBBBBIBBBBBBIBBBOBBBB;BBBBORRBIBBBBBBIBRBBBBBBBBBBBBBBBIBBBBBBBRBOBBBB;BBBBOBRBBIBBBBBBIBBBBBBBBBBBBBBBBBIBBBRRBBBOBBBB;BBBBOBBBBBIBBBBBBIBBBBBBBIIBBRRBBBBIBRRBBBBOBBBB;BBBBOBBBBBDIBBBBBBIBBBBBIBBIBBBBBBBBIBBBBBBOBBBB;BBBBOBBBBBIDIBBBBBBIBBBIBBBBIBBBBBBBBIBBBBBOBBBB;BBBBOBBBBIBBBIBBBBBBIDIBBBBBBIBBBRBBBBIBBBBOBBBB;BBBBOBBBIBBBBBIBBRBBBIBBBBBRBBIBBBBBRBBIBRBOBBBB;BBBBOBBIBBBBBBBRBBBBBBBBRRRBBBBBBBRRBBBBIBBOBBBB;BBBBODIBBBBBBBBRBBBBBBBBBBBBBBBBBBBBBBBRRIDOBBBB;BBBBOIDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBEBBBBDIOBBBB;BBBBOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOBBBB;BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB;BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.'),
	(4, 100, 75, 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB;BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB;BBBBOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOBBBB;BBBBOPBBRBBIRRDDDRBRRBBBBIBBBDRBBBRBDDRBBBDOBBBB;BBBBODRBBBBIBBB  1 BBRRRDIDBBRDRRRBDRBBDRDROBBBB;BBBBORRBBRBIBDB    BRDDRDIDRRBDBBBRBRBBRBRDOBBBB;BBBBOBBBBDBIRBB    BDBBBBIRBBBRRRRBDDRBBRBDOBBBB;BBBBORRBRRDBRBBBBBBBRRRBBIDDBRRRRBBBDRBBBDBOBBBB;BBBBOBBBBBIIIIBBBBBBBIIIBBBBBBIIIBBBBBBBIIIOBBBB;BBBBOB        B         B           B      OBBBB;BBBBOB        BBBB      BBBBB       B      OBBBB;BBBBOB        B             B       B      OBBBB;BBBBOBBBBB    BBBBBBB   BBBBB    BBBBBBB   OBBBB;BBBBOIIIIIIIIIIIIIII        IIIIIIIIIIIIIIIOBBBB;BBBBODDDDDDDDDDDDDDI        IDDDDDDDDDDDDDDOBBBB;BBBBODBBBBBBBBBBBBDI   1    IRRRRRRRRRRRRRROBBBB;BBBBODB     1    BDI        IBBBBBBBBBBBBBBOBBBB;BBBBODBBBBBBBBBBBBDI        I              OBBBB;BBBBORDDDDDDDDDDDDDI        IDDDDDDDDDDDDDDOBBBB;BBBBORRRRRRRRRRRRRRRRRBBBBRRRRRRRRRRRRRRRRROBBBB;BBBBOBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBEOBBBB;BBBBODDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDOBBBB;BBBBORRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRROBBBB;BBBBOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOBBBB;BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB;BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.'),
	(5, 200, 25, 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB;BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB;BBBBOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOBBBB;BBBBO   IIIIBBBBBBBBBBBBBBBBBBBBBBBBBBBDDDDOBBBB;BBBBO P IIIIBBBBBDBDBDBDBBDBBDBDDBDBDBBBBBBOBBBB;BBBBO   IIIIBBBBBBBBBBBBBBBBBBBBBBBBBBI    OBBBB;BBBBOBBBIIIIRIIBBDDBDDBDDBIIIIIIIIIIIIIBBBBOBBBB;BBBBOBBBIIIIRIIBBBBBBBBBBBIBBBBBBBBBBBBBBBBOBBBB;BBBBOBBBIIIIRIIIIIIIIIIIIIIBBRBBBRRBRBBBBBBOBBBB;BBBBOBBBBBBBBBIRDRRBBBBBBBBBBRRRBRRBRRRBBBBOBBBB;BBBBOIIIIIII IIRRRBBBBBBBBBBBBRBBRRBBRBBBBBOBBBB;BBBBOIIIIIII IIDRRBBBBBBBBBBBBBBBBBBBBBBBBBOBBBB;BBBBOIIIIIII IIRRRBBBBBBBIIIIIIIIIIIIIIIIIIOBBBB;BBBBOIIIIIIIIIIRRBBBBIIIIIBBBBBRRRRRBBBBIDBOBBBB;BBBBODIBBBBBBBIRBBBBIIRBBBBBBBBRRRRBBBBBIDBOBBBB;BBBBODIBIBBBBBIBBBBIIDRRBBBBBBBBRRBBBBBBI BOBBBB;BBBBOBIBIBBBRRIBBBBIRRRRBBBBBBBBBBBBBBBBBBBOBBBB;BBBBOBBBIBBBBBBBBBBBRRRRBBBBBBBBBBBBBIIIIBIOBBBB;BBBBOIIBIBBB  BBBBBBBRRBBBBBBBBBBBBBBIBBBBBOBBBB;BBBBODIBIBBB 1BBBBBBBBBBBBBBBBBBBBBBRIBIIIIOBBBB;BBBBODIBIBBBBBIBBBBBBBBRBBBBBBBBBBRRRIBBBBBOBBBB;BBBBOBIBIBBBBBIBBBBBRRRRRBBBBBBBBRRRRIBIBEBOBBBB;BBBBOBBBIBBBBBIBBBBRRRRRRRRBBBBRRRRRRIBIBBBOBBBB;BBBBOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOBBBB;BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB;BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.'),
	(6, 300, 34, 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB;BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB;BBBBOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOBBBB;BBBBOPBBBBBBBDBBBBBBBBBRRBBBBBBBBBBBBBBBBBBOBBBB;BBBBOBBBBBBBBDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBOBBBB;BBBBOIIIIIIIIIIIIIIIII 1  IIIIIIIIIIIIIIIIIOBBBB;BBBBOBBBBBBBBBBBBBBBBI    IBBBBBBBBBBBBBBBBOBBBB;BBBBOBBBBBBBBBBBBBBBBIBRBRIBBBBBBBBBBBBBBBBOBBBB;BBBBOD                  2                 DOBBBB;BBBBOBBRRRRBBBBBBBBBBBBBBBBBBBBBBBRRRRBBBBBOBBBB;BBBBOBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBOBBBB;BBBBO      BBBBBBBBBBBBBBBBBBBBBBB      BBBOBBBB;BBBBO  1   BBBBBBBBBBBBBBBBBBBBBBB   1  BBBOBBBB;BBBBOBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBOBBBB;BBBBOBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBOBBBB;BBBBO                                      OBBBB;BBBBOD                  2                 DOBBBB;BBBBOBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBOBBBB;BBBBOBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBOBBBB;BBBBOBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBOBBBB;BBBBOBBBBBBBBBBBBBBBBBBBBBBBBBBIIIIIIIIIIIIOBBBB;BBBBOBBBBBBBBBBBBBBBRBBBRBBBBRBIRBBBBBBBBBDOBBBB;BBBBOBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBEOBBBB;BBBBOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOBBBB;BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB;BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.'),
	(38, 80, 15, 'I;P;I.'),
	(39, 160, 15, 'BBBBBBBBBBBBBBBBB;BBBBBBBBBBBBBBBBB;BBBBIIIIIIIIIBBBB;BBBBIPR BRR1 BBBB;BBBBIBBR2 BBIBBBB;BBBBIEIIIIIIIBBBB;BBBBBBBBBBBBBBBBB;BBBBBBBBBBBBBBBBB.'),
	(40, 50, 15, 'BBBBBBBBBBBBBBBBBBBB;BBBBBBBBBBBBBBBBBBBB;BBBBIIIIIIIIIIIIBBBB;BBBBIBBBBBBBBBBIBBBB;BBBBIBBR BB DBBIBBBB;BBBBIBB BBB RBBIBBBB;BBBBIBB BBBBBBBIBBBB;BBBBIBBPBBBBBBBIBBBB;BBBBIIIIIIIIIIIIBBBB;BBBBBBBBBBBBBBBBBBBB;BBBBBBBBBBBBBBBBBBBB.'),
	(41, 500, 15, 'BBBBBBBBBBBBBBBBBBBB;BBBBBBBBBBBBBBBBBBBB;BBBBIIIIIIIIIIIIBBBB;BBBBIBBBBBB  1 IBBBB;BBBBIBBR BB    IBBBB;BBBBIBB BBBBBBBIBBBB;BBBBIBBBBBB  2 IBBBB;BBBBIBBPBBB    IBBBB;BBBBIIIIIIIIIIIIBBBB;BBBBBBBBBBBBBBBBBBBB;BBBBBBBBBBBBBBBBBBBB.');
/*!40000 ALTER TABLE `level` ENABLE KEYS */;

-- Export de la structure de la procédure boulder_dash. SelectID
DROP PROCEDURE IF EXISTS `SelectID`;
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `SelectID`(
	IN `i` INT
)
    READS SQL DATA
    SQL SECURITY INVOKER
SELECT * FROM level WHERE id = i//
DELIMITER ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
